services:
  telegram-social-bot:
    build:
      context: .
    container_name: telegram-social-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/tmp/telegram-social-bot
